domain_path: G:\FPGA\try_and_error\Zybo-logic-gate-demo\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: G:\Aplikasi\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
